name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image from DockerHub
      run: docker pull aindi123/hello-world-python:0.0.1.RELEASE

    - name: Create environment file
      run: echo "IMAGE_TAG=aindi123/hello-world-python:0.0.1.RELEASE" >> $GITHUB_ENV

    - name: Run Docker container
      run: docker run -d -p 8080:8080 ${{ env.IMAGE_TAG }}

    - name: Pull Trivy Docker image
      run: docker pull aquasec/trivy:latest

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v $(pwd):/workdir aquasec/trivy:latest --quiet image ${{ env.IMAGE_TAG }} > scan_results.txt
