name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image from DockerHub
      run: docker pull aindi123/hello-world-python:0.0.1.RELEASE

    - name: Set Docker image tag
      run: |
        echo ::set-env name=IMAGE_TAG::aindi123/hello-world-python:0.0.1.RELEASE

    - name: Run Docker container
      run: docker run -d -p 8080:8080 $IMAGE_TAG
